# Generated by Django 3.1.2 on 2020-10-26 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Query',
        ),
    ]
